StokTakipSistemi/StokTakipSistemi/Controllers/AdminStokController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StokTakipSistemi.Models;
namespace StokTakipSistemi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminStokController : Controller
    {
        StokTakipSistemiDBEntities db = new StokTakipSistemiDBEntities();
        public ActionResult Index()
        {
            var model = db.tblStok.ToList();
            return View(model);
        }
        public ActionResult UrunAl()
        {
            var model = new ViewModels.UrunParca();
            model.ParcaTipleri = db.tblParcaTipi.ToList();
            return View(model);
        }
        [ValidateAntiForgeryToken]
        public ActionResult Ekle(ViewModels.UrunParca model)
        {
            // burada genel ürünü dbye ekliyoruz,stok'a ekliyoruz ve adet sayısı kadar ürün oluşturuyoruz.
            if (ModelState.IsValid)
            {     // burada genel ürünü dbye ekliyoruz,stok'a ekliyoruz ve adet sayısı kadar ürün oluşturuyoruz.

                model.Urun.urunSatinAlmaTarih = DateTime.Now;
                model.Urun.urunToplamFİyat = model.Urun.urunFiyat * model.Urun.urunAdet;
                model.Urun.Aktiflik = true;

                db.tblUrunGenel.Add(model.Urun);
                db.SaveChanges();

                tblUrun urun = new tblUrun();
                urun.urunAd = model.Urun.urunAd;
                urun.urunSatinAlmaTarih = model.Urun.urunSatinAlmaTarih;
                urun.urunFiyat = model.Urun.urunFiyat;
                urun.urunGenelId = model.Urun.urunGenelId;
                urun.satinAlinanKurum = model.Urun.satinAlinanKurum;
                urun.urunParcaId = model.Urun.urunParcaId;
                urun.Aktiflik = true;

                for (int i = 0; i < model.Urun.urunAdet; i++)
                {
                    db.tblUrun.Add(urun);
                    db.SaveChanges();
                }

                tblStok stok = new tblStok();
                stok.urunGenelId = model.Urun.urunGenelId;
                db.tblStok.Add(stok);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                model.ParcaTipleri = db.tblParcaTipi.ToList();
                return View("UrunAl", model);
            }

        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            if (id > 0)
            { // id hatasız ise buraya girecektir.
                ViewModels.UrunParca model = new ViewModels.UrunParca();
                var genelurun = db.tblUrunGenel.FirstOrDefault(m => m.urunGenelId == id);
                if (genelurun != null)
                {  // güncellenecek model bulunduysa sistem buraya girecektir
                    model.Urun = genelurun;
                    model.ParcaTipleri = db.tblParcaTipi.ToList();
                    return View(model);
                }
                else
                {  // güncellenecek model bulunmadıysa sistem buraya girecektir
                    return HttpNotFound();
                }

            }
            else
            {  // id hatalı ise sistem bad request hatası verecektir.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guncelle(ViewModels.UrunParca model)
        {
            if (ModelState.IsValid)
            {  
                if (model.Urun.urunGenelId>0)
                {
                    var eskigenelurun = db.tblUrunGenel.FirstOrDefault(m => m.urunGenelId == model.Urun.urunGenelId);
                    if (eskigenelurun != null)
                    {    //model validationları sağladığı takdirde buraya girecektir
                        //güncelleme işlemi bu if bloğunda gerçekleşmektedir
                        foreach (var urun in eskigenelurun.tblUrun.ToList())
                        {
                            if (urun.zimmetDurumu == null && urun.zimmetDurumu == null)
                            {
                                db.tblUrun.Remove(urun);
                                db.SaveChanges();
                            }
                        }
                        eskigenelurun.urunAd = model.Urun.urunAd;
                        eskigenelurun.urunAdet = model.Urun.urunAdet;
                        eskigenelurun.urunFiyat = model.Urun.urunFiyat;
                        eskigenelurun.urunParcaId = model.Urun.urunParcaId;
                        eskigenelurun.satinAlinanKurum = model.Urun.satinAlinanKurum;
                        eskigenelurun.urunToplamFİyat = model.Urun.urunFiyat * model.Urun.urunAdet;
                        db.SaveChanges();


                        var urn = new Models.tblUrun();
                        urn.urunAd = model.Urun.urunAd;
                        urn.urunFiyat = model.Urun.urunFiyat;
                        urn.urunParcaId = model.Urun.urunParcaId;
                        urn.urunGenelId = model.Urun.urunGenelId;
                        urn.satinAlinanKurum = model.Urun.satinAlinanKurum;
                        urn.Aktiflik = true;
                        urn.urunSatinAlmaTarih = DateTime.Now;

                        for (int i = 0; i < model.Urun.urunAdet; i++)
                        {
                            db.tblUrun.Add(urn);
                            db.SaveChanges();
                        }
                        return RedirectToAction("Index");
                        
                    }
                    else
                    {   // eski güncellenecek ürün bulunmdıysa not found hataso verecektir
                        return HttpNotFound();
                    }
                    

                }
                else
                {   // ürün id'si hatalı ise sistem badrequest hatası verecektir.
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                
            }
            else
            {  //model validationları sağlamıyorsa geri döndürülmektedir.
                model.ParcaTipleri = db.tblParcaTipi.ToList();
                return View("Guncelle", model);
            }


        }
       
        [HttpGet]
        public ActionResult Zimmetle(int id)
        {   
            if (id > 0)
            {  
                var model = new ViewModels.UrunDepartman();
                model.Departmanlar = db.tblDepartman.ToList();
                model.Urun = db.tblUrunGenel.FirstOrDefault(m => m.urunGenelId == id);
                if (model.Urun != null)
                {
                    return View(model);
                }
                else
                {
                    //model bulunamadıysa not found hatası döndürülecektir
                    return HttpNotFound();
                }
            }
            else
            {   // gönderilen id hatalı iste bad request hatası döndürülecektir
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Zimmetle(ViewModels.UrunDepartman model, int persid)
        {
            if (persid > 0)
            {
                var personel = db.tblPersonel.FirstOrDefault(m => m.personelId == persid);
                if (personel != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (model.Urun.urunGenelId > 0)
                        {
                            var GenelUrun = db.tblUrunGenel.FirstOrDefault(m => m.urunGenelId == model.Urun.urunGenelId);

                            if (GenelUrun != null && GenelUrun.Aktiflik == true)
                            {  // model tüm validationları sağladığında buraya düşecek işlem gerçekleşecektir
                                GenelUrun.urunAdet--;
                                GenelUrun.urunToplamFİyat = GenelUrun.urunFiyat * GenelUrun.urunAdet;
                                db.SaveChanges();

                                if (GenelUrun.urunAdet == 0)
                                {   // urun adeti 0 lanmış ise stoktan düşme işleminin gerçekleştirildiği blok tur.
                                    var stok = db.tblStok.FirstOrDefault(m => m.urunGenelId == GenelUrun.urunGenelId);
                                    db.tblStok.Remove(stok);
                                    db.SaveChanges();
                                }

                                var Zimmet = new tblZimmet();
                                foreach (var urun in GenelUrun.tblUrun)
                                {
                                    if (urun.zimmetDurumu == null)
                                    {
                                        urun.zimmetDurumu = true;
                                        Zimmet.urunId = urun.urunId;
                                        break;
                                    }
                                }
                                Zimmet.personelId = personel.personelId;
                                db.tblZimmet.Add(Zimmet);
                                db.SaveChanges();
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                return HttpNotFound();
                            }
                        }
                        else
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                    }
                    else
                    {
                        model.Departmanlar = db.tblDepartman.ToList();
                        return View("Zimmetle", model);
                    }
                 }

StokTakipSistemi/StokTakipSistemi/Views/AdminStok/Guncelle.cshtml
@model StokTakipSistemi.ViewModels.UrunParca
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Guncelle", "AdminStok", FormMethod.Post))
{<div class="adminrender">
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunAd)
            @Html.TextBoxFor(m => m.Urun.urunAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunAd)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunFiyat)
            @Html.TextBoxFor(m => m.Urun.urunFiyat, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunFiyat)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunParcaId)
            @Html.DropDownListFor(m => m.Urun.urunParcaId, new SelectList(Model.ParcaTipleri, "urunParcaId", "parcaTipi"), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunParcaId)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunAdet)
            @Html.TextBoxFor(m => m.Urun.urunAdet, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunAdet)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.satinAlinanKurum)
            @Html.TextBoxFor(m => m.Urun.satinAlinanKurum, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.satinAlinanKurum)
        </div>

        @Html.HiddenFor(m => m.Urun.urunGenelId)
        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-default">Güncelle</button>
</div>
}

StokTakipSistemi/StokTakipSistemi/Views/AdminStok/Index.cshtml
@model List<StokTakipSistemi.Models.tblStok>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <style>
        .search {
            margin-left: 880px;
            width: 170px;
            border: 1px  solid blue;
            border-width: thin;
            margin-bottom: 10px;
            border-radius: 10px;
        }
    </style>
</head>
<body >
    <div class="adminrender">
        @if (Model != null)
    {<a class="btn btn-success" href="/AdminStok/UrunAl">Ürün Al</a>
        <input type="text" name="arama" class="search " placeholder="Ara..." />


        <table class="adminrender table table-hover stoktable">
            <tr>
                <th>Ürün Adı</th>
                <th>Satın Alma Tarihi</th>
                <th>Birim Fiyatı</th>
                <th>Toplam Fiyatı</th>
                <th>Parça tipi</th>
                <th>Ürün Adeti</th>
                <th>Satın Alınan Kurum</th>
                <th></th>
            </tr>
            @foreach (var stok in Model)
        {
            <tr>
                <td>@stok.tblUrunGenel.urunAd</td>
                <td>@stok.tblUrunGenel.urunSatinAlmaTarih</td>
                <td>@stok.tblUrunGenel.urunFiyat<span class="simge-tl"> &#8378;</span></td>
                <td>@stok.tblUrunGenel.urunToplamFİyat<span class="simge-tl"> &#8378;</span></td>
                <td>@stok.tblUrunGenel.tblParcaTipi.parcaTipi</td>
                <td>@stok.tblUrunGenel.urunAdet</td>
                <td>@stok.tblUrunGenel.satinAlinanKurum</td>
                <td>
                    <a href="/AdminStok/Guncelle/@stok.urunGenelId" class="btn btn-primary">Güncelle</a>
                    <a href="/AdminStok/Zimmetle/@stok.urunGenelId" class="btn btn-primary">Zimmetle</a>
                </td>
            </tr>
    }

        </table>

}
else
{
    <table class="table table-hover">
        <tr>
            <th>Ürün Adı</th>
            <th>Satın Alma Tarihi</th>
            <th>Toplam Fiyatı</th>
            <th>Parça tipi</th>
            <th>Ürün Adeti</th>
            <th>Satın Alınan Kurum</th>
            <th></th>
        </tr>
    </table>
}
    </div>
</body>

StokTakipSistemi/StokTakipSistemi/Views/AdminStok/UrunAl.cshtml
@model StokTakipSistemi.ViewModels.UrunParca
@{
    ViewBag.Title = "UrunAl";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Ekle", "AdminStok", FormMethod.Post))
{<div class="adminrender">
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunAd)
            @Html.TextBoxFor(m => m.Urun.urunAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunAd)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunFiyat)
            @Html.TextBoxFor(m => m.Urun.urunFiyat, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunFiyat)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunParcaId)
            @Html.DropDownListFor(m => m.Urun.urunParcaId, new SelectList(Model.ParcaTipleri, "urunParcaId", "parcaTipi"))
            @Html.ValidationMessageFor(m => m.Urun.urunParcaId)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.urunAdet)
            @Html.TextBoxFor(m => m.Urun.urunAdet, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.urunAdet)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Urun.satinAlinanKurum)
            @Html.TextBoxFor(m => m.Urun.satinAlinanKurum, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Urun.satinAlinanKurum)
        </div>
        @Html.AntiForgeryToken()
        <button class="btn btn-default" type="submit">Satın Al</button>
 </div>
    }

StokTakipSistemi/StokTakipSistemi/Views/AdminStok/Zimmetle.cshtml
@model StokTakipSistemi.ViewModels.UrunDepartman
@{
    ViewBag.Title = "Zimmetle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Zimmetle", "AdminStok", FormMethod.Post, new { enctype = "multipart/form-data" }))
{<div class="adminrender">
    <div class="form-group">
        @Html.LabelFor(m => m.Urun.urunAd)
        @Html.TextBoxFor(m => m.Urun.urunAd, new { @class = "form-control", @readonly = "true" })
        @Html.ValidationMessageFor(m => m.Urun.urunAd)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Urun.urunSatinAlmaTarih)
        @Html.TextBoxFor(m => m.Urun.urunSatinAlmaTarih, new { @class = "form-control", @readonly = "true" })
        @Html.ValidationMessageFor(m => m.Urun.urunSatinAlmaTarih)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Urun.urunFiyat)
        @Html.TextBoxFor(m => m.Urun.urunFiyat, new { @class = "form-control", @readonly = "true" })
        @Html.ValidationMessageFor(m => m.Urun.urunFiyat)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Urun.tblParcaTipi.parcaTipi)
        @Html.TextBoxFor(m => m.Urun.tblParcaTipi.parcaTipi, new { @class = "form-control", @readonly = "true" })
        @Html.ValidationMessageFor(m => m.Urun.tblParcaTipi)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Urun.satinAlinanKurum)
        @Html.TextBoxFor(m => m.Urun.satinAlinanKurum, new { @class = "form-control", @readonly = "true" })
        @Html.ValidationMessageFor(m => m.Urun.satinAlinanKurum)
    </div>
    <div class="form-group">
        <select class="admindep form-control">
            @foreach (var departman in Model.Departmanlar)
            {
                <option value="@departman.departmanId">@departman.departmanAd</option>
            }
        </select>
    </div>
    <div class="form-group persbox">
        <select class="adminpers form-control" name="persid">
            @foreach (var per in Model.Departmanlar.First().tblPersonel)
            {
                <option value="@per.personelId">@per.personelAd   @per.personelSoyad  @per.SGKNO</option>
            }

        </select>
        <label id="valid"></label>
    </div>
     @Html.HiddenFor(m => m.Urun.urunGenelId)
    @Html.HiddenFor(m => m.Urun.urunParcaId)
    @Html.HiddenFor(m => m.Urun.urunAdet)

    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-default AdminzimmetleBtn">ZİMMETLE</button>
   </div>
}