StokTakipSistemi/StokTakipSistemi/Controllers/SAPersonelController.cs
using StokTakipSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace StokTakipSistemi.Controllers
{
    [Authorize(Roles = "Satın Alma")]
    public class SAPersonelController : Controller
    {
        StokTakipSistemiDBEntities db = new StokTakipSistemiDBEntities();
        public ActionResult Index()
        {  // tüm personeller listelenerek model halinde view'a gönderilmektedir.
            var model = db.tblPersonel.ToList();
            return View(model);
        }
        public ActionResult Urunler(int personelid)
        {
            if (personelid > 0)
            {
                var model = db.tblPersonel.FirstOrDefault(m => m.personelId == personelid);
                if (model != null)
                {   var urunler = new List<Models.tblUrun>();
                    var Zimmetler = model.tblZimmet;
                    foreach (var zimmet in model.tblZimmet)
                    {
                        var urun = db.tblUrun.First(x => x.urunId == zimmet.urunId);
                        urunler.Add(urun);
                    }
                    return View(urunler);
                }
                else
                {   // model bulunamadıysa notfound hatası döndürülmektedir
                    return HttpNotFound();
                }
            }
            else
            {
                // personelid hatalı ise sistem bad request döndürmektedir.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }
        
        public ActionResult ZimmetKaldir(int id)
        {
            //buraya gelen id ürünnün id sidir burada zimmetden düşülüp atık tablosuna eklenir
            if (id > 0)
            {   // id 0 dan büyük ise bu if bloğu aktif olacaktır
                var atik = new Models.tblAtikKontrol();
                var urun = db.tblUrun.FirstOrDefault(m => m.urunId == id);
                if (urun != null)
                {
                    var zimmet = db.tblZimmet.FirstOrDefault(m => m.urunId == id);
                    if (zimmet != null)
                    {  // zimmet null değilse burası çalışacaktır
                        urun.zimmetDurumu = false;
                        urun.Aktiflik = false;

                        bool test = false;
                        foreach (var atIk in db.tblAtikKontrol.ToList())
                        {
                            if (atIk.tblUrun.urunGenelId == urun.urunGenelId)
                                test = true;
                        }

                        if (!test)
                        {
                            atik.urunId = urun.urunId;
                            atik.atikurunAdet = 1;
                            db.tblAtikKontrol.Add(atik);
                            db.SaveChanges();
                        }
                        else
                        {
                            foreach (var Atik in db.tblAtikKontrol.ToList())
                            {
                                if (Atik.tblUrun.urunGenelId == urun.urunGenelId)
                                {
                                    Atik.atikurunAdet++;
                                    db.SaveChanges();
                                }
                            }
                        }
                        db.tblZimmet.Remove(zimmet);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {  // sistem zimmet bulunamadığı için not found döndürecektir.
                        return HttpNotFound();
                    }

                }
                else
                {
                    //sistem model bulunamadığından dolayı not found hatası döndürecektir.
                    return HttpNotFound();
                }

            }
            else
            {  // id hatalı ise sistem badrequest döndürecektir.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }
    }
}

StokTakipSistemi/StokTakipSistemi/Views/SAPersonel/Index.cshtml
@model List<StokTakipSistemi.Models.tblPersonel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        .SAsearchPer {
            margin-left: 900px;
            width: 170px;
            height: 30px;
            border: 1px solid blue;
            border-width: thin;
            border-radius: 10px;
        }
     
    </style>
</head>
 
<body >
    <div class="SAPersonelFoto">
        <input type="text" name="arama" class="SAsearchPer" placeholder="Ara.." />
        <table class="table table-hover SATablePer">
            <tr>
                <th>Personel Adı</th>
                <th>Personel Soyadı</th>
                <th>Personel Aktifliği</th>
                <th>Departmanı</th>
                <th>SGKNO</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var personel in Model)
        {
            <tr>
                <td>@personel.personelAd</td>
                <td>@personel.personelSoyad</td>
                <td>@personel.Aktiflik</td>
                <td>@personel.tblDepartman.departmanAd</td>
                @if (personel.tblZimmet.Count != 0)
            {
                <td>@personel.SGKNO</td>
                <td>
                    @Ajax.ActionLink("Zimmetli Ürunler", "Urunler", "SAPersonel",
                                new { personelid = personel.personelId }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "urunlistesi" },
                                new { @class = "btn btn-danger" })
                </td>
        }
        else
        {
            <td>@personel.SGKNO</td>
    }
            </tr>
    }

        </table>
        <div id="urunlistesi">
        </div>
    </div>
</body>

StokTakipSistemi/StokTakipSistemi/Views/SAPersonel/Urunler.cshtml
@model List<StokTakipSistemi.Models.tblUrun>
@{
    Layout =null;
}
<table class="table table-hover">
    <tr>
        <th>Ürün Adı</th>
        <th>Satın Alma Tarihi</th>
        <th>Ürün Fiyatı</th>
        <th>Parça tipi</th>
        <th>Satın Alınan Kurum</th>
        <th></th>
    </tr>
    @foreach(var urun in Model)
    {
        <tr>
            <td>@urun.urunAd</td>
            <td>@urun.urunSatinAlmaTarih</td>
            <td>@urun.urunFiyat<span class="simge-tl"> &#8378;</span></td>
            <td>@urun.tblUrunGenel.tblParcaTipi.parcaTipi</td>
            <td>@urun.satinAlinanKurum</td>
            <td>
                
               <a href="/SAPersonel/ZimmetKaldir/@urun.urunId" class="btn btn-warning">Zimmeti Kaldır</a>
            </td>
        </tr>
    }

</table>